-- MySaveTheDate — Contenu initial de la FAQ du chatbot (100 questions/réponses)
-- Ce script est autonome : il crée la table si elle n'existe pas encore
-- (identique à la définition de supabase-setup.sql), puis insère les 100
-- questions/réponses UNIQUEMENT si la table est vide (ré-exécutable sans
-- risque de duplication, y compris après en avoir édité le contenu).

CREATE TABLE IF NOT EXISTS msd_faq (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  categorie   TEXT DEFAULT '',
  ordre       INTEGER DEFAULT 0,
  question    TEXT NOT NULL,
  reponse     TEXT NOT NULL,
  active      BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE msd_faq ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_msd_faq_ordre ON msd_faq(ordre);

INSERT INTO msd_faq (categorie, ordre, question, reponse, active)
SELECT * FROM (VALUES
('Découverte du service', 1, 'Qu''est-ce que MySaveTheDate ?', 'MySaveTheDate est un service qui crée pour vous un faire-part numérique personnalisé (site web) pour votre mariage, Bar/Bat Mitsva, anniversaire ou autre événement, avec gestion des réponses des invités, mur de photos et vidéos.', true),
('Découverte du service', 2, 'Pour quels types d''événements MySaveTheDate est-il adapté ?', 'Mariages, Bar Mitsva, Bat Mitsva, anniversaires, Brit Mila et autres célébrations peuvent tous être créés sur MySaveTheDate, avec un contenu adapté à chaque type d''événement.', true),
('Découverte du service', 3, 'Ai-je besoin de savoir coder pour utiliser MySaveTheDate ?', 'Non, aucune compétence technique n''est nécessaire. Vous répondez à un questionnaire puis personnalisez votre faire-part depuis un éditeur visuel simple, sans une ligne de code.', true),
('Découverte du service', 4, 'Combien de temps faut-il pour créer mon faire-part ?', 'Un premier aperçu de votre faire-part est généré automatiquement en quelques minutes, juste après avoir répondu au questionnaire. Vous pouvez ensuite le personnaliser à votre rythme.', true),
('Découverte du service', 5, 'Puis-je essayer avant de payer ?', 'Oui. Vous pouvez prévisualiser gratuitement votre faire-part généré à partir du questionnaire, avant de décider de le personnaliser ou de débloquer son partage.', true),
('Découverte du service', 6, 'Le faire-part est-il visible par mes invités dès sa création ?', 'Non. Votre faire-part reste privé tant que vous n''avez pas choisi une formule payante pour débloquer son partage.', true),
('Découverte du service', 7, 'Puis-je créer plusieurs faire-part avec un seul compte ?', 'Oui, un même compte peut gérer plusieurs faire-part (par exemple pour plusieurs événements), chacun avec son propre sous-domaine et sa propre formule.', true),
('Découverte du service', 8, 'Le faire-part fonctionne-t-il sur mobile ?', 'Oui, chaque faire-part est conçu pour s''afficher correctement aussi bien sur smartphone, tablette que sur ordinateur.', true),
('Découverte du service', 9, 'Puis-je changer d''avis sur le type d''événement après avoir commencé ?', 'Oui, vous pouvez modifier le type d''événement, les textes et les pages activées à tout moment depuis votre éditeur, avant ou après le déblocage du partage.', true),
('Découverte du service', 10, 'Où puis-je voir un exemple de faire-part ?', 'Un aperçu réel est généré dès que vous complétez le questionnaire sur le site : vous voyez immédiatement le rendu final avec vos propres informations.', true),
('Créer son faire-part', 11, 'Comment créer mon faire-part ?', 'Cliquez sur "Créer mon faire-part" sur le site, répondez au questionnaire (type d''événement, date, lieu, style, pages souhaitées) puis prévisualisez le résultat généré automatiquement.', true),
('Créer son faire-part', 12, 'Que dois-je renseigner dans le questionnaire ?', 'Le type d''événement, la date, le lieu, une palette de couleurs, les informations sur le sujet du faire-part (les mariés, l''enfant fêté...) et les pages que vous souhaitez activer.', true),
('Créer son faire-part', 13, 'Qui est "le sujet" du faire-part ?', 'C''est la ou les personnes concernées par l''événement (les mariés, l''enfant pour une Bar/Bat Mitsva...), qui peuvent être différentes de la personne qui remplit le questionnaire (parent, témoin...).', true),
('Créer son faire-part', 14, 'Puis-je remplir le questionnaire pour quelqu''un d''autre ?', 'Oui, par exemple un parent peut créer le faire-part de la Bar Mitsva de son enfant, ou un témoin peut créer celui d''un mariage.', true),
('Créer son faire-part', 15, 'Que se passe-t-il juste après le questionnaire ?', 'Un faire-part complet est généré automatiquement avec vos informations, un sous-domaine personnalisé et un thème de couleurs. Vous arrivez directement sur un aperçu réel.', true),
('Créer son faire-part', 16, 'Puis-je recommencer le questionnaire si je me trompe ?', 'Oui, vous pouvez relancer le questionnaire ; les informations pourront ensuite être ajustées ou corrigées directement dans l''éditeur.', true),
('Créer son faire-part', 17, 'Dois-je créer un compte avant de voir mon faire-part ?', 'Non, l''aperçu est généré sans compte. La connexion ou l''inscription n''est demandée que lorsque vous souhaitez le personnaliser davantage ou le partager.', true),
('Créer son faire-part', 18, 'Comment récupérer le faire-part que j''ai créé sans compte ?', 'Dès que vous vous connectez ou créez votre compte depuis la page d''aperçu, ce faire-part est automatiquement rattaché à votre compte.', true),
('Créer son faire-part', 19, 'Puis-je choisir les pages de mon faire-part (hommage, Shabbat, infos, vidéo, RSVP) ?', 'Oui, le questionnaire vous permet de cocher les pages que vous souhaitez activer, et vous pouvez les activer/désactiver ou les réordonner plus tard dans l''éditeur.', true),
('Créer son faire-part', 20, 'Puis-je changer la musique choisie pendant le questionnaire ?', 'Oui, la musique de fond peut être changée à tout moment depuis votre éditeur.', true),
('Personnalisation', 21, 'Comment accéder à l''éditeur de mon faire-part ?', 'Connectez-vous à votre espace personnel, ouvrez votre faire-part depuis le tableau de bord, puis choisissez "Personnaliser".', true),
('Personnalisation', 22, 'Puis-je changer les couleurs de mon faire-part ?', 'Oui, plusieurs palettes de couleurs sont proposées, et vous pouvez aussi personnaliser vos propres couleurs si vous le souhaitez.', true),
('Personnalisation', 23, 'Puis-je modifier tous les textes du faire-part ?', 'Oui, tous les textes (titres, phrases d''invitation, informations pratiques...) sont modifiables librement depuis l''éditeur.', true),
('Personnalisation', 24, 'Puis-je changer l''ordre des pages de mon faire-part ?', 'Oui, l''ordre des pages (faire-part, hommage, Shabbat, informations, vidéo, RSVP) peut être réorganisé depuis l''éditeur.', true),
('Personnalisation', 25, 'Puis-je activer ou désactiver une page après la création ?', 'Oui, chaque page (hommage, Shabbat, informations complémentaires, vidéo, RSVP) peut être activée ou désactivée à tout moment.', true),
('Personnalisation', 26, 'Comment ajouter des photos à mon faire-part ?', 'Depuis l''éditeur, vous pouvez importer vos photos directement dans les sections concernées de votre faire-part.', true),
('Personnalisation', 27, 'Puis-je changer la date ou le lieu de mon événement après création ?', 'Oui, ces informations restent modifiables à tout moment dans l''éditeur, même après le déblocage du partage.', true),
('Personnalisation', 28, 'Mes modifications sont-elles enregistrées automatiquement ?', 'Oui, chaque modification apportée dans l''éditeur est sauvegardée, avec une confirmation visuelle de l''enregistrement.', true),
('Personnalisation', 29, 'Puis-je prévisualiser mon faire-part avant de le partager ?', 'Oui, un aperçu réel est disponible à tout moment depuis l''éditeur, identique à ce que verront vos invités une fois le partage débloqué.', true),
('Personnalisation', 30, 'Puis-je changer le sous-domaine (l''adresse) de mon faire-part ?', 'Le sous-domaine est généré automatiquement à partir des prénoms/noms renseignés ; contactez le support si vous souhaitez le modifier.', true),
('Personnalisation', 31, 'Puis-je personnaliser la page "Informations complémentaires" ?', 'Oui, vous pouvez choisir un contenu prédéfini (visa, hébergement, tenue, liste de cadeaux) ou rédiger votre propre texte et lien.', true),
('Personnalisation', 32, 'Comment fonctionne la page "Hommage" ?', 'Elle est proposée par défaut pour les Bar/Bat Mitsva et peut être personnalisée ou désactivée depuis l''éditeur selon vos souhaits.', true),
('Personnalisation', 33, 'Puis-je adapter le contenu religieux (Shabbat, bénédiction hébraïque) à mon événement ?', 'Oui, ce contenu, pensé pour les Bar/Bat Mitsva, est entièrement modifiable ou désactivable si votre événement n''en a pas besoin.', true),
('Personnalisation', 34, 'Que faire si je ne trouve pas une option dans l''éditeur ?', 'N''hésitez pas à me poser la question précisément ici, ou à contacter le support à contact@mysavethedate.fr si besoin d''une fonctionnalité spécifique.', true),
('Formules et tarifs', 35, 'Quelles sont les formules disponibles ?', 'Trois formules à paiement unique : Essentiel (30€, jusqu''à 30 invités), Populaire (120€, jusqu''à 200 invités, avec vidéo), et Premium (220€, jusqu''à 400 invités, avec vidéo et mur de photos inclus).', true),
('Formules et tarifs', 36, 'Quelle formule choisir pour un petit événement ?', 'La formule Essentiel (30€) convient bien pour un événement jusqu''à 30 invités, sans vidéo ni mur de photos.', true),
('Formules et tarifs', 37, 'Quelle formule choisir pour une Bar/Bat Mitsva ?', 'La formule Populaire (120€) est pensée pour ce type d''événement, avec jusqu''à 200 invités inclus et la vidéo activée.', true),
('Formules et tarifs', 38, 'Quelle formule choisir pour un mariage ?', 'La formule Premium (220€) est recommandée pour un mariage : jusqu''à 400 invités inclus, avec vidéo et mur de photos inclus.', true),
('Formules et tarifs', 39, 'Les formules sont-elles des abonnements ?', 'Non, il s''agit d''un paiement unique pour débloquer le partage de votre faire-part, pas d''un abonnement récurrent.', true),
('Formules et tarifs', 40, 'Que se passe-t-il si j''ai plus d''invités que prévu dans ma formule ?', 'Vous pouvez recevoir plus de réponses que votre quota inclus ; un supplément (5€ de base + 1,50€ par réponse au-delà du quota) permet de débloquer l''accès à toutes les réponses.', true),
('Formules et tarifs', 41, 'La vidéo est-elle incluse dans toutes les formules ?', 'Non, la vidéo est incluse dans les formules Populaire et Premium, mais pas dans la formule Essentiel.', true),
('Formules et tarifs', 42, 'Le mur de photos est-il inclus dans toutes les formules ?', 'Il est inclus uniquement dans la formule Premium. Pour les autres formules, il est disponible en option payante (29,99€).', true),
('Formules et tarifs', 43, 'Puis-je changer de formule après l''achat ?', 'Contactez le support à contact@mysavethedate.fr pour étudier un changement de formule selon votre situation.', true),
('Formules et tarifs', 44, 'Les prix affichés sont-ils toutes taxes comprises ?', 'Oui, les prix affichés dans votre espace client sont en euros, toutes taxes comprises le cas échéant.', true),
('Paiement', 45, 'Comment se passe le paiement ?', 'Le paiement est traité de façon sécurisée via Stripe, un prestataire de paiement tiers reconnu. Vous êtes redirigé vers une page de paiement sécurisée pour entrer vos informations bancaires.', true),
('Paiement', 46, 'MySaveTheDate stocke-t-il mes coordonnées bancaires ?', 'Non, aucune donnée bancaire n''est stockée par MySaveTheDate : le paiement est intégralement géré par Stripe.', true),
('Paiement', 47, 'Quand mon faire-part devient-il visible après paiement ?', 'Dès que le paiement est confirmé par Stripe, votre faire-part est automatiquement activé et devient accessible à vos invités.', true),
('Paiement', 48, 'Puis-je me faire rembourser après le déblocage du partage ?', 'Le déblocage du partage est un contenu numérique fourni immédiatement après la commande ; conformément à nos CGU, le droit de rétractation de 14 jours ne s''applique pas une fois l''achat validé.', true),
('Paiement', 49, 'Que faire si mon paiement échoue ?', 'Vérifiez vos informations bancaires et réessayez. Si le problème persiste, contactez contact@mysavethedate.fr.', true),
('Paiement', 50, 'Puis-je payer plusieurs faire-part séparément ?', 'Oui, chaque faire-part dispose de sa propre formule et de son propre paiement, indépendamment des autres faire-part de votre compte.', true),
('Paiement', 51, 'Le paiement du supplément RSVP est-il définitif ?', 'Oui, une fois payé, le déblocage des réponses au-delà du quota reste acquis, y compris pour les réponses reçues après coup.', true),
('Paiement', 52, 'Puis-je obtenir une facture ?', 'Contactez contact@mysavethedate.fr pour toute demande de facture liée à votre paiement.', true),
('Partage et invités', 53, 'Comment partager mon faire-part avec mes invités ?', 'Une fois le partage débloqué, vous pouvez transmettre le lien de votre faire-part ou son code QR à vos invités, par exemple par message ou par carton d''invitation.', true),
('Partage et invités', 54, 'Qu''est-ce que le code QR de mon faire-part ?', 'C''est un code que vos invités peuvent scanner avec leur téléphone pour accéder directement à votre faire-part en ligne. Il est disponible dans votre espace une fois le faire-part publié.', true),
('Partage et invités', 55, 'Quelle est l''adresse de mon faire-part ?', 'Chaque faire-part dispose d''une adresse unique du type prenom-nom.mysavethedate.com, générée automatiquement à partir des informations du sujet de l''événement.', true),
('Partage et invités', 56, 'Mes invités ont-ils besoin d''un compte pour voir le faire-part ?', 'Non, vos invités accèdent librement au faire-part via le lien ou le code QR, sans avoir besoin de créer de compte.', true),
('Partage et invités', 57, 'Puis-je envoyer le lien par email directement depuis mon espace ?', 'Oui, un raccourci est disponible pour préparer un email d''invitation avec le lien de votre faire-part.', true),
('Partage et invités', 58, 'Combien de personnes peuvent consulter mon faire-part ?', 'Il n''y a pas de limite au nombre de personnes qui peuvent consulter votre faire-part ; la limite concerne uniquement le nombre de réponses RSVP incluses dans votre formule.', true),
('Partage et invités', 59, 'Puis-je désactiver temporairement mon faire-part ?', 'Contactez le support à contact@mysavethedate.fr si vous souhaitez suspendre temporairement l''accès public à votre faire-part.', true),
('Partage et invités', 60, 'Le faire-part reste-t-il en ligne après l''événement ?', 'Oui, votre faire-part et les réponses de vos invités restent accessibles depuis votre espace tant que votre compte n''est pas supprimé.', true),
('RSVP', 61, 'Qu''est-ce que le RSVP ?', 'C''est la page où vos invités confirment leur présence, indiquent le nombre d''adultes et d''enfants qui les accompagnent, et peuvent laisser un message.', true),
('RSVP', 62, 'Où puis-je voir les réponses de mes invités ?', 'Toutes les réponses RSVP sont visibles depuis votre tableau de bord, dans l''espace dédié à votre faire-part.', true),
('RSVP', 63, 'Puis-je exporter la liste de mes invités et leurs réponses ?', 'Oui, vous pouvez exporter vos réponses RSVP au format CSV directement depuis votre espace.', true),
('RSVP', 64, 'Puis-je gérer plusieurs événements dans le RSVP (par exemple cérémonie et Shabbat) ?', 'Oui, le RSVP peut gérer plusieurs événements distincts (cérémonie, réception, Shabbat...), chaque invité répondant pour chacun.', true),
('RSVP', 65, 'Que se passe-t-il si je reçois plus de réponses que mon quota inclus ?', 'Les réponses au-delà du quota restent comptabilisées mais peuvent être verrouillées jusqu''à ce que vous régliez le supplément correspondant.', true),
('RSVP', 66, 'Comment débloquer les réponses RSVP au-delà de mon quota ?', 'Depuis votre tableau de bord, vous pouvez régler le supplément affiché (5€ de base + 1,50€ par réponse excédentaire) pour débloquer l''accès à toutes les réponses.', true),
('RSVP', 67, 'Mes invités peuvent-ils modifier leur réponse RSVP après l''avoir envoyée ?', 'Chaque soumission crée une nouvelle réponse ; pour toute correction, votre invité peut vous contacter directement ou soumettre à nouveau le formulaire.', true),
('RSVP', 68, 'Les invités peuvent-ils laisser un message avec leur réponse ?', 'Oui, un champ message est disponible sur le formulaire RSVP pour que vos invités puissent vous laisser un mot.', true),
('RSVP', 69, 'Puis-je désactiver la page RSVP ?', 'Oui, comme les autres pages, le RSVP peut être désactivé depuis l''éditeur si vous ne souhaitez pas collecter de réponses en ligne.', true),
('RSVP', 70, 'Les réponses RSVP sont-elles confidentielles ?', 'Oui, seules les personnes ayant accès à votre espace personnel peuvent consulter les réponses de vos invités.', true),
('Mur de photos', 71, 'Qu''est-ce que le mur de photos ?', 'C''est une galerie collaborative où vos invités peuvent déposer eux-mêmes des photos et vidéos prises pendant votre événement, visibles ensuite par tous.', true),
('Mur de photos', 72, 'Le mur de photos est-il inclus dans ma formule ?', 'Il est inclus dans la formule Premium ; pour les formules Essentiel et Populaire, il est disponible en option à 29,99€.', true),
('Mur de photos', 73, 'Comment mes invités déposent-ils des photos sur le mur ?', 'Ils accèdent à une page d''envoi dédiée depuis le faire-part, sans avoir besoin de créer de compte.', true),
('Mur de photos', 74, 'Y a-t-il une limite au nombre de photos sur le mur ?', 'Il n''y a pas de limite stricte annoncée ; le mur est conçu pour recevoir l''ensemble des photos et vidéos partagées par vos invités.', true),
('Mur de photos', 75, 'Puis-je modérer les photos déposées sur le mur ?', 'Contactez contact@mysavethedate.fr si un contenu déposé doit être retiré ; MySaveTheDate se réserve le droit de retirer tout contenu manifestement illicite.', true),
('Mur de photos', 76, 'Puis-je activer le mur de photos après l''événement ?', 'Oui, vous pouvez débloquer l''option mur de photos à tout moment depuis votre espace, avant ou après votre événement.', true),
('Mur de photos', 77, 'Le mur de photos fonctionne-t-il aussi pour les vidéos ?', 'Oui, vos invités peuvent y déposer aussi bien des photos que des vidéos.', true),
('Mur de photos', 78, 'Puis-je télécharger les photos du mur ?', 'Les photos et vidéos du mur restent accessibles depuis votre faire-part ; pour un export groupé, contactez contact@mysavethedate.fr.', true),
('Vidéo et musique', 79, 'Comment fonctionne la fonctionnalité vidéo ?', 'Vos invités peuvent enregistrer et envoyer un message vidéo directement depuis votre faire-part, que vous retrouvez ensuite dans votre espace.', true),
('Vidéo et musique', 80, 'La fonctionnalité vidéo est-elle incluse dans toutes les formules ?', 'Non, elle est incluse dans les formules Populaire et Premium, mais pas dans la formule Essentiel.', true),
('Vidéo et musique', 81, 'Où puis-je voir les vidéos envoyées par mes invités ?', 'Toutes les vidéos reçues sont accessibles depuis votre tableau de bord.', true),
('Vidéo et musique', 82, 'Puis-je ajouter ma propre musique de fond ?', 'Oui, vous pouvez importer votre propre musique lors du questionnaire ou depuis l''éditeur.', true),
('Vidéo et musique', 83, 'Puis-je avoir une musique différente selon les pages de mon faire-part ?', 'Oui, l''éditeur permet d''associer des musiques différentes à certaines pages si vous le souhaitez.', true),
('Vidéo et musique', 84, 'Quels formats de musique sont acceptés ?', 'Les formats audio courants sont acceptés (comme le MP3) via l''import de fichier dans l''éditeur.', true),
('Compte, sécurité et support', 85, 'Comment créer mon compte ?', 'Vous pouvez créer un compte avec votre email et un mot de passe, ou en un clic via "Continuer avec Google", depuis la page de connexion de votre espace.', true),
('Compte, sécurité et support', 86, 'J''ai oublié mon mot de passe, que faire ?', 'Cliquez sur "Mot de passe oublié" sur l''écran de connexion : vous recevrez un lien par email pour en choisir un nouveau.', true),
('Compte, sécurité et support', 87, 'Puis-je me connecter avec mon compte Google ?', 'Oui, le bouton "Continuer avec Google" permet de créer ou retrouver votre compte en un clic, sans mot de passe à retenir.', true),
('Compte, sécurité et support', 88, 'Mes données sont-elles en sécurité ?', 'Oui, l''accès à votre espace est protégé par mot de passe chiffré (ou connexion Google) et par un jeton d''authentification sécurisé.', true),
('Compte, sécurité et support', 89, 'Qui a accès à mon faire-part et à mes réponses RSVP ?', 'Seul votre compte a accès à votre espace de gestion ; vos invités ne voient que la version publique du faire-part une fois le partage débloqué.', true),
('Compte, sécurité et support', 90, 'Puis-je supprimer mon compte ?', 'Oui, vous pouvez demander la suppression de votre compte et de vos données à tout moment en nous contactant à contact@mysavethedate.fr.', true),
('Compte, sécurité et support', 91, 'Que deviennent mes données si je supprime mon compte ?', 'Vos données personnelles sont supprimées ou anonymisées dans un délai raisonnable, hors obligations légales de conservation (comptables notamment).', true),
('Compte, sécurité et support', 92, 'Comment contacter le support MySaveTheDate ?', 'Vous pouvez nous écrire à contact@mysavethedate.fr pour toute question qui dépasse ce que je peux vous indiquer ici.', true),
('Compte, sécurité et support', 93, 'Le service est-il disponible 24h/24 ?', 'L''accès à votre espace et à votre faire-part est disponible en continu, sauf maintenance ou incident technique ponctuel, sans garantie de disponibilité ininterrompue.', true),
('Compte, sécurité et support', 94, 'J''ai un bug ou un problème technique, que faire ?', 'Décrivez-moi le problème rencontré, ou contactez contact@mysavethedate.fr avec le maximum de détails (ce que vous avez fait, ce qui s''est affiché).', true),
('Compte, sécurité et support', 95, 'Puis-je changer l''adresse email de mon compte ?', 'Contactez contact@mysavethedate.fr pour toute demande de changement d''adresse email associée à votre compte.', true),
('Compte, sécurité et support', 96, 'Mes invités peuvent-ils accidentellement modifier mon faire-part ?', 'Non, seuls les titulaires du compte connectés à l''espace personnel peuvent modifier le faire-part ; vos invités ne voient que la version publique.', true),
('Compte, sécurité et support', 97, 'Puis-je utiliser MySaveTheDate depuis n''importe quel pays ?', 'Oui, le service est accessible en ligne depuis n''importe où, tant que vous disposez d''une connexion internet.', true),
('Compte, sécurité et support', 98, 'MySaveTheDate revend-il mes données à des tiers ?', 'Non, aucune donnée n''est vendue à des tiers à des fins commerciales, conformément à notre politique de confidentialité.', true),
('Compte, sécurité et support', 99, 'Quels sont mes droits sur mes données personnelles (RGPD) ?', 'Vous disposez d''un droit d''accès, de rectification, d''effacement, de limitation, d''opposition et de portabilité de vos données, en nous contactant à contact@mysavethedate.fr.', true),
('Compte, sécurité et support', 100, 'Où puis-je lire les conditions générales et la politique de confidentialité ?', 'Ces documents sont accessibles en bas de page du site, dans les rubriques "Mentions légales", "Conditions générales" et "Confidentialité & RGPD".', true)
) AS v(categorie, ordre, question, reponse, active)
WHERE NOT EXISTS (SELECT 1 FROM msd_faq);
